all: search

search:  lab4_start.o lab4_util.o lab4_main.o 
	ld -m elf_x86_64 -o search lab4_start.o lab4_util.o lab4_main.o  

lab4_start.o: lab4_start.s
	nasm -g -f elf64 lab4_start.s -o lab4_start.o

lab4_util.o: lab4_util.c
	gcc -g -m64 -Wall -ansi -c -nostdlib -fno-stack-protector lab4_util.c -o lab4_util.o

lab4_main.o: lab4_main.c
	gcc -g -m64 -Wall -ansi -c -nostdlib -fno-stack-protector lab4_main.c -o lab4_main.o 


clean:
	rm -f *.o
